### ISSUE TITLE
Anleitung für Einheitsleiter

### ISSUE THREAD

**Issue by holtzchopf** [Tripplefix/rela16#14]

**Comment by rbuetzer** [comment]
Mail von Cambia:

> nur um auch sicher zu gehen, dass die Kommunikation zu den ELs vollständig ist: Jegliche Wald- und Wiesenstücke MÜSSEN über das Online-Tool gebucht werden. Es werden im Lager selbst auch spontan noch Waldstücke zur Verfügung stehen. Es ist jedoch nicht erlaubt, einfach in den Wald zu spazieren und dort sein Programm abzuhalten, ohne dass man vorher das entsprechende Waldstück gebucht hat.

> Die Info war im Teleskop ebenfalls nicht eindeutig und ich möchte einfach sichergehen, dass jetzt in dieser Phase keine Missverständnisse aufkommen.

**Comment by rbuetzer** [comment]
Input Cambia: ELs darauf hinweisen, dass Angebote bis 31. Mai gebucht werden müssen.

**Comment by rbuetzer** [comment]
Habe den Edit-Link mal noch Cambia geschickt. Sie wird dann möglicherweise auch noch mithelfen.
